server.port=8099

# Enable WebFlux reactive gateway
spring.cloud.gateway.server.webflux.enabled=true

# Order Service Route
spring.cloud.gateway.server.webflux.routes[0].id=order-service
spring.cloud.gateway.server.webflux.routes[0].uri=lb://order-service
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/order-service/**
spring.cloud.gateway.server.webflux.routes[0].filters[0]=StripPrefix=1

# Inventory Service Route
spring.cloud.gateway.server.webflux.routes[1].id=inventory-service
spring.cloud.gateway.server.webflux.routes[1].uri=lb://inventory-service
spring.cloud.gateway.server.webflux.routes[1].predicates[0]=Path=/inventory-service/**
spring.cloud.gateway.server.webflux.routes[1].filters[0]=StripPrefix=1

# Cart Service Route
spring.cloud.gateway.server.webflux.routes[2].id=cart-service
spring.cloud.gateway.server.webflux.routes[2].uri=lb://cart-service
spring.cloud.gateway.server.webflux.routes[2].predicates[0]=Path=/cart-service/**
spring.cloud.gateway.server.webflux.routes[2].filters[0]=StripPrefix=1

# ========== Tracing settings ==========
# Always sample 100% of traces
management.tracing.sampling.probability=1.0

# Send traces to Jaeger BE
management.otlp.tracing.endpoint=http://${JAEGER_HOST:localhost}:${JAEGER_PORT:4318}/v1/traces

# Enable trace propagation
management.tracing.propagation.type=W3C
management.tracing.propagation.produce=W3C
management.tracing.propagation.consume=W3C

# Eureka settings
eureka.instance.prefer-ip-address=true
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.client.serviceUrl.defaultZone=http://${EUREKA_HOST:localhost}:${EUREKA_PORT:8761}/eureka/
